#!/bin/sh

if [[ $# -eq 0 || $1 = "-e=prod" || $1 = "--env=prod" ]]; then
    npm install --only=prod
    npm run prod

elif [[ $1 = "-e=dev" || $1 = "--env=dev" ]]; then
    npm install
    npm run watch-poll
    
else
    exec "$@"
fi
